name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Determine image tags and labels
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.GCLOUD_REPO_URL }}
        tags: |
          type=ref,enable=true,event=branch,suffix=--{{sha}}
          type=ref,enable=true,event=branch,suffix=--latest
          type=ref,event=tag
          type=ref,event=pr
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: cloud
        endpoint: ${{ secrets.DBC_BUILDER_NAME }}

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider:  ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: ">= 363.0.0"

    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        provenance: mode=max
        sbom: true
        push: true
        load: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # - name: Deploy test image
    #   run: |
    #     gcloud run deploy cats --region=us-east1 --image=docker.io/mikesir87/cats:3.0 --port 5000
